### ISSUE TITLE
Mistake-proofing enhancement?

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [stefanhh0/aosp-10#8]
We know to perform a build, this command is required:

```
env SOURCE=~/android/sony LUNCH_CHOICE=aosp_g8142-userdebug PLATFORM=yoshino DEVICE=maple ./build-4.14.sh -x
```

And here are the hardware related variable:

```
PLATFORM
DEVICE
```

If these two are not set, I think the script should refuse to run instead of place a default value?  
ummmm... because I just build and installed a `yoshino & lilac` to `yoshino & maple` device.  
Because of that, now I lost my userdata lol

**Comment by stefanhh0** [comment]
Hey @mhtvsSFrpHdE,

thanks for opening that issue. The only var that requires to be provided is `LUNCH_CHOICE`. `PLATFORM` and `DEVICE` are no longer in use in the latest version of the script.

You are right that `LUNCH_CHOICE` should not be set to a default.

> Because of that, now I lost my userdata lol

I am sorry for your loss, I hope you have a backup of your files.

Cheers, Stefan

**Comment by stefanhh0** [comment]
Fixed with commit: https://github.com/stefanhh0/aosp-10/commit/2c0c362d47862005a5b9b9a7bd380bb69cb145d1

**Comment by mhtvsSFrpHdE** [comment]
They still exist in `-h` help section... so now latest version if I run

```
env SOURCE=~/android/sony LUNCH_CHOICE=aosp_g8142-userdebug ./build-4.14.sh -x
```
Without specifying `PLATFORM` and `DEVICE` it will do build with the correct kernel ?

**Comment by stefanhh0** [comment]
Well `PLATFORM` and `DEVICE` are no longer in the script. Please double check that you are on commit: 2c0c362d47862005a5b9b9a7bd380bb69cb145d1. Since I always force-push you may have merged something. In case you haven't changed anything yourself use `git fetch && git reset --hard origin/master`. In case you have your own commits, you should branch them off, do the hard reset and then cherry-pick them accordingly.

If you are using the correct version on the script then it will build the correct kernel when specifying `LUNCH_CHOICE`. You can also simply call `./build-4.14.sh -x` it'll then ask for the configuration to build.
